### PR TITLE
Simplify GitHub CI configuration

### PR DESCRIPTION
**Pull request by chshersh**
Just an experiment to see whether it works.

### CODE REVIEW

**Review by vrom911 — APPROVED** [review]
Will it make it even quicker? :racehorse:

**Comment by chshersh** [comment]
@vrom911 Looks like it's finally working as expected! Apparently, the problem was in the following:

Only `~/.cabal/store` needs to be cached. Other cache directories took too much space and ate all our free space for cache. So `.cabal/store` wasn't restored and that's why all dependencies were built from scratch each time. It should be much faster now (from 3 minutes to 1 minute).

**Comment by vrom911** [comment]
@chshersh should we patch `Summoner` as well?

**Comment by chshersh** [comment]
@vrom911 Yes, we definitely should patch `Summoner`.

**Pull request merged**
